### PR TITLE
revised logo, adapted typography / figures

### PR DESCRIPTION
**Pull request by drfho**
Hi,
the pages now use the facelifted logo. Typography as well as some pictures (as svg) are adapted to the logo. 
Looking forward to a updated zope.de-website
Regards
f

screenshot

### CODE REVIEW

**Review by dataflake — APPROVED** [review]

**Comment by dataflake** [comment]
Looking good, but personally I don't know where it's hosted or who is maintaining it.

**Comment by icemac** [comment]
@loechel Are you able to deploy those changes once they are merged?

**Comment by loechel** [comment]
It is hosted / manged by the Plone AI Team  @plone/ai-team maybe @ericof or @polyester could make a deployment

**Comment by polyester** [comment]
deployed (ahem, it's just "git pull" on the server) and refreshed cloudflare.

**Pull request merged**
