### PR TITLE
Google Analytics tracking code

### PR DESCRIPTION
**Pull request by ericof**
Add tracking with Google Analytics, as requested to the Plone Foundation Board

### CODE REVIEW

**Comment by dataflake** [comment]
I'm not a contributor to this specific repository, but since this website is targeted at a EU audience I would at least do some research about those Google spying mechanisms and what needs to change on at least the page about data protection so the site is not running afoul of the EU GDPR regulation (see https://en.wikipedia.org/wiki/General_Data_Protection_Regulation). 

At the very least the page `datenschutz.html` must be amended to clearly say that "yes, you are being spied on" and "yes, the spying results are shipped to a company outside the EU".

**Comment by ericof** [comment]
@dataflake I agree with you. @loechel, would you mind taking a look at this?

**Comment by loechel** [comment]
Hi @ericof, I will look into it, and will make the necessary modifications, But I will not be able to do it today, hopefully on the weekend.

Alexander

**Comment by dataflake** [comment]
Data protection agencies in Europe are moving towards considering Google Analytics as breaching European GDPR provisions, starting with Austria in January 2022 (https://www.theregister.com/2022/01/13/google_analytics_gdpr/) and now France (https://www.theregister.com/2022/02/10/google_analytics_gdpr_breach/). I suggest you close this PR and drop any plans to use Google Analytics on any site that is targeted at an audience in the EU.

**Comment by ericof** [comment]
Closing because it is no longer relevant

**Pull request closed without merging**
